dependencies:
  - OpenZeppelin/openzeppelin-contracts@1.7.0
compiler:
  solc:
    remappings:
     - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@1.7.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}